const tokenAuth =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzU3ZWJlMjhlYzczN2EzZTUxMzhkZSIsImlhdCI6MTY5MDcyOTMyMCwiZXhwIjoxNjkwODE1NzIwfQ.n5Jwmbb2F18KhFSojz4iadHA0VyXwDB57-zgD4UaePM";

export default tokenAuth;
