const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YzU3ZWJlMjhlYzczN2EzZTUxMzhkZSIsImlhdCI6MTY5MDcxNTUxOCwiZXhwIjoxNjkwODAxOTE4fQ.fj-jMegb4-imkrSeLqVa0NeZ-2FGp92ZJiI1Zl6zMHA";

export default token;
